//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomReservationClient.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cninnovation.com/RoomReservation/2016", ConfigurationName="ServiceRef.IRoomService")]
    public interface IRoomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cninnovation.com/RoomReservation/2016/IRoomService/ReserveRoom", ReplyAction="http://www.cninnovation.com/RoomReservation/2016/IRoomService/ReserveRoomResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(RoomReservationContracts.RoomReservationFault), Action="http://www.cninnovation.com/RoomReservation/2016/IRoomService/ReserveRoomRoomRese" +
            "rvationFaultFault", Name="RoomReservationFault", Namespace="http://schemas.datacontract.org/2004/07/RoomReservationContracts")]
        bool ReserveRoom(RoomReservationContracts.RoomReservation roomReservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cninnovation.com/RoomReservation/2016/IRoomService/ReserveRoom", ReplyAction="http://www.cninnovation.com/RoomReservation/2016/IRoomService/ReserveRoomResponse" +
            "")]
        System.Threading.Tasks.Task<bool> ReserveRoomAsync(RoomReservationContracts.RoomReservation roomReservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cninnovation.com/RoomReservation/2016/IRoomService/GetRoomReservations" +
            "", ReplyAction="http://www.cninnovation.com/RoomReservation/2016/IRoomService/GetRoomReservations" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(RoomReservationContracts.RoomReservationFault), Action="http://www.cninnovation.com/RoomReservation/2016/IRoomService/GetRoomReservations" +
            "RoomReservationFaultFault", Name="RoomReservationFault", Namespace="http://schemas.datacontract.org/2004/07/RoomReservationContracts")]
        RoomReservationContracts.RoomReservation[] GetRoomReservations(System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cninnovation.com/RoomReservation/2016/IRoomService/GetRoomReservations" +
            "", ReplyAction="http://www.cninnovation.com/RoomReservation/2016/IRoomService/GetRoomReservations" +
            "Response")]
        System.Threading.Tasks.Task<RoomReservationContracts.RoomReservation[]> GetRoomReservationsAsync(System.DateTime fromDate, System.DateTime toDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomServiceChannel : RoomReservationClient.ServiceRef.IRoomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomServiceClient : System.ServiceModel.ClientBase<RoomReservationClient.ServiceRef.IRoomService>, RoomReservationClient.ServiceRef.IRoomService {
        
        public RoomServiceClient() {
        }
        
        public RoomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ReserveRoom(RoomReservationContracts.RoomReservation roomReservation) {
            return base.Channel.ReserveRoom(roomReservation);
        }
        
        public System.Threading.Tasks.Task<bool> ReserveRoomAsync(RoomReservationContracts.RoomReservation roomReservation) {
            return base.Channel.ReserveRoomAsync(roomReservation);
        }
        
        public RoomReservationContracts.RoomReservation[] GetRoomReservations(System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.GetRoomReservations(fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<RoomReservationContracts.RoomReservation[]> GetRoomReservationsAsync(System.DateTime fromDate, System.DateTime toDate) {
            return base.Channel.GetRoomReservationsAsync(fromDate, toDate);
        }
    }
}
